<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4979" started-at="2023-02-14T22:49:15 CST" finished-at="2023-02-14T22:49:20 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4979" started-at="2023-02-14T22:49:15 CST" finished-at="2023-02-14T22:49:20 CST">
      <class name="test.ValidateCategoryTest">
        <test-method status="PASS" signature="checkAddCategory()[pri:0, instance:test.ValidateCategoryTest@6acdbdf5]" name="checkAddCategory" duration-ms="2913" started-at="2023-02-14T22:49:15 CST" finished-at="2023-02-14T22:49:18 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkAddCategory -->
        <test-method status="FAIL" signature="checkDuplicatecategory()[pri:0, instance:test.ValidateCategoryTest@6acdbdf5]" name="checkDuplicatecategory" duration-ms="2028" started-at="2023-02-14T22:49:18 CST" finished-at="2023-02-14T22:49:20 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The category you want to add already exists expected [testCategory8] but found [testCategory9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The category you want to add already exists expected [testCategory8] but found [testCategory9]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at page.ValidateAddCategory.checkDuplicateCategory(ValidateAddCategory.java:39)
at test.ValidateCategoryTest.checkDuplicatecategory(ValidateCategoryTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDuplicatecategory -->
      </class> <!-- test.ValidateCategoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
